GAME_TITLE = "Miniature Nemesis"
GAME_VERSION = "0.1a"

WIN_WIDTH = 640
WIN_HEIGHT = 360
WIN_TITLE = "%s v%s" % (GAME_TITLE, GAME_VERSION)

DIFFICULTY_EASY = 1
DIFFICULTY_NORMAL = 2
DIFFICULTY_HARD = 4
DIFFICULTY_WTF = 8

SPEED_FACTORS = {
        DIFFICULTY_EASY: 0.8,
        DIFFICULTY_NORMAL: 1.0,
        DIFFICULTY_HARD: 1.4,
        DIFFICULTY_WTF: 2.2
}

SPEED_BASE = 100

SPEED_EASY = int(SPEED_BASE * SPEED_FACTORS[DIFFICULTY_EASY])
SPEED_NORMAL = int(SPEED_BASE * SPEED_FACTORS[DIFFICULTY_NORMAL])
SPEED_HARD = int(SPEED_BASE * SPEED_FACTORS[DIFFICULTY_HARD])
SPEED_WTF = int(SPEED_BASE * SPEED_FACTORS[DIFFICULTY_WTF])