GAME_TITLE = "Miniature Nemesis"
GAME_VERSION = "0.1a"

WIN_WIDTH = 640
WIN_HEIGHT = 360
WIN_TITLE = "%s v%s" % (GAME_TITLE, GAME_VERSION)

EASY = 1
NORMAL = 2
HARD = 4

SPEED_FACTORS = {
        EASY: 0.8,
        NORMAL: 1.0,
        HARD: 1.4,
}

SPEED_BASE = 100

SPEED_EASY = int(SPEED_BASE * SPEED_FACTORS[EASY])
SPEED_NORMAL = int(SPEED_BASE * SPEED_FACTORS[NORMAL])
SPEED_HARD = int(SPEED_BASE * SPEED_FACTORS[HARD])